import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Bookmark, ChevronDown, Film, Heart, Menu, MoreVertical, Play, Search, Share2, X, Youtube } from "lucide-react";
import { toast } from "sonner";

type Video = { id: string; title: string; creator: string; thumbnail: string; url?: string; publishedAt?: string; avatar: string; durationSeconds?: number; viewCount?: number; likeCount?: number };
const initials = (name: string) => name.split(/\s|\//).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "YT";
const compactNumber = (value?: number) => new Intl.NumberFormat("vi-VN", { notation: "compact", maximumFractionDigits: 1 }).format(value ?? 0);
const toggleLocal = (key: string, id: string) => { const ids = new Set<string>(JSON.parse(localStorage.getItem(key) || "[]")); ids.has(id) ? ids.delete(id) : ids.add(id); localStorage.setItem(key, JSON.stringify(Array.from(ids))); };
const shareVideo = async (video: Video) => { const url = `https://www.youtube.com/watch?v=${video.id}`; if (navigator.share) await navigator.share({ title: video.title, url }); else await navigator.clipboard?.writeText(url); };
function Avatar({ value, className = "" }: { value: string; className?: string }) { return <span className={`avatar ${className}`}>{value}</span>; }
function Shell({ children, onShorts, search, setSearch }: { children: ReactNode; onShorts: () => void; search: string; setSearch: (value: string) => void }) { return <div className="yt-app"><aside className="yt-sidebar"><div className="yt-side-top"><button className="yt-wordmark" onClick={() => { window.location.href = "/"; }}><span className="yt-logo"><Play size={14} fill="currentColor" /></span><strong>streamly</strong></button></div><div className="yt-side-scroll"><button className="yt-nav-item" onClick={onShorts}><Film size={21} /><span>Video ngắn</span></button></div><div className="yt-side-footer">Giới thiệu · Báo chí · Bản quyền · Liên hệ<br />Điều khoản · Quyền riêng tư · An toàn<div className="yt-copyright">© 2026 Streamly</div></div></aside><div className="yt-main"><header className="yt-header"><button className="yt-icon-btn yt-hamburger" aria-label="Mở menu"><Menu size={23} /></button><button className="yt-mobile-wordmark yt-wordmark" onClick={() => { window.location.href = "/"; }}><span className="yt-logo"><Play size={13} fill="currentColor" /></span><strong>streamly</strong></button><div className="yt-search"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm kiếm" aria-label="Tìm kiếm" />{search && <button aria-label="Xóa tìm kiếm" onClick={() => setSearch("")}><X size={17} /></button>}<button className="yt-search-btn" aria-label="Tìm kiếm"><Search size={21} /></button></div><div className="yt-header-actions"><span className="yt-profile"><Avatar value="MC" className="yt-profile-avatar" /></span></div></header>{children}</div></div>; }
function VideoCard({ video, onOpen }: { video: Video; onOpen: (video: Video) => void }) { return <article className="yt-video-card" onClick={() => onOpen(video)}><button className="yt-thumbnail" aria-label={`Phát ${video.title}`}><img src={video.thumbnail} alt="" /><span className="yt-duration">{video.durationSeconds ? `${Math.floor(video.durationSeconds / 60)}:${String(video.durationSeconds % 60).padStart(2, "0")}` : "HD"}</span><span className="yt-play"><Play size={18} fill="currentColor" /></span></button><div className="yt-card-info"><div className="yt-card-copy"><h3>{video.title}</h3><p>{video.creator} <span className="verified-check">✓</span></p><span>{compactNumber(video.viewCount)} lượt xem · {compactNumber(video.likeCount)} lượt thích · {video.publishedAt ? new Date(video.publishedAt).toLocaleDateString("vi-VN") : "Mới đây"}</span><div className="video-actions"><button onClick={(e) => { e.stopPropagation(); toggleLocal("streamly-liked", video.id); }} aria-label="Thích"><Heart size={14} /> Thích</button><button onClick={(e) => { e.stopPropagation(); toggleLocal("streamly-saved", video.id); }} aria-label="Lưu"><Bookmark size={14} /> Lưu</button><button onClick={(e) => { e.stopPropagation(); void shareVideo(video); }} aria-label="Chia sẻ"><Share2 size={14} /> Chia sẻ</button></div></div><button className="yt-card-menu" aria-label="Thao tác khác" onClick={(e) => { e.stopPropagation(); toast("Các thao tác khác sẽ sớm ra mắt"); }}><MoreVertical size={18} /></button></div></article>; }
export default function Home() {
  const { isAuthenticated, loading: authLoading } = useAuth();
  const connection = trpc.youtube.connection.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const feedQuery = trpc.youtube.feed.useQuery(undefined, { enabled: isAuthenticated && Boolean(connection.data?.connected), retry: false });
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Video | null>(null);
  const searchQuery = trpc.youtube.search.useQuery({ query: search.trim() }, { enabled: isAuthenticated && Boolean(connection.data?.connected) && search.trim().length >= 2, retry: false });
  const connect = () => { if (authLoading) return; if (!isAuthenticated) return startLogin(); window.location.href = "/api/youtube/oauth/start"; };
  useEffect(() => { const status = new URLSearchParams(window.location.search).get("youtube"); if (status === "connected") { toast.success("YouTube đã được kết nối"); void connection.refetch(); void feedQuery.refetch(); window.history.replaceState({}, "", "/"); } }, []);
  const videos = useMemo(() => (feedQuery.data?.videos ?? []).map((video) => ({ id: video.id, title: video.title, creator: video.creator, thumbnail: video.thumbnail, url: video.url, publishedAt: video.publishedAt, durationSeconds: video.durationSeconds, viewCount: video.viewCount, likeCount: video.likeCount, avatar: initials(video.creator) })), [feedQuery.data]);
  const query = search.trim().toLocaleLowerCase("vi-VN");
  const searchVideos = useMemo(() => (search.trim().length >= 2 ? (searchQuery.data?.videos ?? []).map((video) => ({ ...video, avatar: initials(video.creator) })) : videos), [search, searchQuery.data, videos]);
  const filtered = searchVideos.filter((video) => !query || `${video.title} ${video.creator}`.toLocaleLowerCase("vi-VN").includes(query));
  const connected = Boolean(connection.data?.connected);
  useEffect(() => { const value = search.trim(); if (value.length >= 2) { const old = JSON.parse(localStorage.getItem("streamly-search-history") || "[]") as string[]; localStorage.setItem("streamly-search-history", JSON.stringify([value, ...old.filter((item) => item !== value)].slice(0, 10))); } }, [search]);
  const openVideo = (video: Video) => { setSelected(video); const old = JSON.parse(localStorage.getItem("streamly-watch-history") || "[]") as string[]; localStorage.setItem("streamly-watch-history", JSON.stringify([video.id, ...old.filter((id) => id !== video.id)].slice(0, 20))); };
  return <Shell search={search} setSearch={setSearch} onShorts={() => { window.location.href = "/shorts"; }}><main className="yt-content"><section className={`yt-personal-banner ${connected ? "connected" : ""}`}><div className="yt-personal-icon"><Youtube size={27} /></div><div className="yt-personal-copy"><span>{connected ? "YOUTUBE CỦA BẠN" : "CHÀO MỪNG ĐẾN STREAMLY"}</span><h1>{connected ? `Mới nhất từ ${connection.data?.channelTitle || "các kênh bạn đăng ký"}` : "Bài đăng mới nhất ở ngay đây."}</h1><p>{connected ? `${videos.length} video mới nhất từ các kênh bạn theo dõi.` : "Kết nối YouTube để xem bài đăng và video mới nhất."}</p></div><button className="yt-connect-btn" onClick={connect}>{connected ? "Làm mới kết nối" : "Kết nối YouTube"}<ChevronDown size={16} /></button></section><div className="yt-section-heading yt-personal-heading"><h2>{query ? `Kết quả tìm kiếm cho “${search}”` : "Bài đăng mới nhất"}</h2><button onClick={() => void feedQuery.refetch()}>Làm mới <span>↻</span></button></div>{feedQuery.isLoading ? <div className="yt-loading"><span /><span /><span /></div> : feedQuery.error ? <div className="yt-empty"><Search size={24} /><h3>Không thể tải bài đăng</h3><p>{feedQuery.error.message}</p><button onClick={() => void feedQuery.refetch()}>Thử lại</button></div> : connected && filtered.length ? <div className="yt-video-grid">{filtered.map((video) => <VideoCard key={video.id} video={video} onOpen={openVideo} />)}</div> : <div className="yt-empty"><Youtube size={24} /><h3>{query ? "Không tìm thấy kết quả" : "Chưa có bài đăng mới"}</h3><p>{query ? `Không có bài đăng nào khớp với “${search}”.` : "Kết nối YouTube để hiển thị các bài đăng mới nhất."}</p><button onClick={connect}>{connected ? "Làm mới" : "Kết nối YouTube"}</button></div>}{selected && <div className="video-viewer-backdrop" role="dialog" aria-modal="true" onClick={() => setSelected(null)}><div className="video-viewer" onClick={(e) => e.stopPropagation()}><button className="video-viewer-close" aria-label="Đóng" onClick={() => setSelected(null)}>×</button><iframe src={`https://www.youtube.com/embed/${selected.id}?autoplay=1&rel=0`} title={selected.title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /><div className="video-viewer-copy"><h2>{selected.title}</h2><p>{selected.creator}</p><div className="video-actions viewer-actions"><button onClick={() => toggleLocal("streamly-liked", selected.id)}><Heart size={16} /> Thích</button><button onClick={() => toggleLocal("streamly-saved", selected.id)}><Bookmark size={16} /> Lưu</button><button onClick={() => void shareVideo(selected)}><Share2 size={16} /> Chia sẻ</button></div></div></div></div>}<footer className="yt-footer"><span>Giới thiệu</span><span>Điều khoản</span><span>Quyền riêng tư</span><span>Trợ giúp</span><span className="yt-footer-brand">Streamly · Video hay, không ồn ào.</span></footer></main></Shell>;
}
